name: build-sign-scan
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  supply-chain:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # for keyless signing (Cosign OIDC)
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set image meta
        id: meta
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository }}/app:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.IMAGE }}

      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.meta.outputs.IMAGE }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Scan CVE (Grype)
        uses: anchore/scan-action@v4
        id: grype
        with:
          image: ${{ steps.meta.outputs.IMAGE }}
          fail-build: false

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image with keyless (OIDC)
        run: cosign sign --yes ${{ steps.meta.outputs.IMAGE }}

      - name: Attach SBOM as OCI artifact
        run: cosign attach sbom --sbom sbom.spdx.json ${{ steps.meta.outputs.IMAGE }}

      - name: Save Grype findings
        run: echo '${{ steps.grype.outputs.json }}' > grype.json

      - name: Policy check (OPA/Rego)
        uses: open-policy-agent/opa-action@v2
        with:
          policy-path: ci/policies
          data-path: .
          input: grype.json

      - name: Enforce policy
        run: |
          opa eval -i grype.json -d ci/policies 'data.release.allow' | grep -q 'true' ||           (echo 'Policy denied release due to High/Critical CVEs'; exit 1)
